services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./logs/:/app/logs/
    environment:
      - POSTGRESQL_URL=postgres://postgres:popo@postgres:5432/capi
    depends_on:
      - postgres
  postgres:
    image: postgres:17-bookworm
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=popo
      - POSTGRES_USER=postgres
      - POSTGRES_DB=capi
 