services:
  app:
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./logs/:/app/logs/
      - ./static/:/app/static/
    environment:
      - POSTGRESQL_URL=postgres://postgres:popo@postgres:5432/capi
      # - REDIS_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:17-bookworm
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=popo
      - POSTGRES_USER=postgres
      - POSTGRES_DB=capi
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=2
 