services:
  postgres:
    image: postgres:17-bookworm
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=popo
      - POSTGRES_USER=postgres
      - POSTGRES_DB=capi
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=timmy